### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by bwlang** [kensung-lab/hypo#1]
I would like to try out your new polishing method.
I've been working getting all your build deps available on my high ram machine - but now I've run out of time to actually try the tool.

A bioconda package would be helpful - maybe tricky due to your recent compiler needs, but I guess that's the point ;)
I'll get back to it soon I hope.

**Comment by Ritu-Kundu** [comment]
Hi Brad! Thanks for giving our polisher a try. We are working on Conda recipe to make Hypo's installation a smooth process. Hopefully, we should be able to get it packaged soon enough.

**Comment by Ritu-Kundu** [comment]
Hi Brad!

We have finally made the conda package available. Instructions are in README file. Hope you will have a smooth installation! :)
