### ISSUE TITLE
Mixing short read, linked-reads, and long read datasets

### ISSUE THREAD

**Issue by bbrunet** [kensung-lab/hypo#15]
Hi,
I have short read data from sequencing on a HiSeq 2500 and 10X linked reads from HiSeq X. Both are PE 2 x 150bp but obviously different coverage levels. Should I run these along with the PacBio Sequel II data that I have, by:
a) concatenating them, estimating the combined coverage and then running them together with the PacBio data; or
b) inputting them in separate HyPo runs; or
c) can each be included on separate lines in a single input file? If so, how would their separate coverage levels be provided in the command?

Also, its not clear if raw data should be provided as input to HyPo or if the short read data should be cleaned, error corrected, and paired-ends merged. If the latter, the same question above applies, how should merged and unmerged short read data be supplied as input to HyPo?

Thanks,
Bryan

**Comment by Ritu-Kundu** [comment]
Hi Bryan,

Thanks for using Hypo. Hypo currently doesn't use paired-end info for short reads and treat them as individual reads. It means that HiSeq2500 and linked reads can be combined together as short reads input with their coverage set as the combined coverage (i.e your strategy a). 

As for cleaning, it is usually a good idea to to clean the Illumina reads before using them in any downstream analysis. 
Whole point of polishing is to avoid the expensive step (especially for large genomes like human) of error-correcting the reads, although error-corrected reads will yield better results. If one has error-corrected reads available, we would recommend using them but it is not a pre-requisite as such.
There is absolutely no need to merge the paired-end reads for Hypo.

Hope that helps.

**Comment by bbrunet** [comment]
Perfect, thanks for the clarification!
