### ISSUE TITLE
No Ns allowed?

### ISSUE THREAD

**Issue by drk0311** [kensung-lab/hypo#4]
Hi, 

Does hypo not expect any Ns in the draft assembly?

I'm trying to polish my draft assembly (done by Flye) with hypo but it ends up with error at [Hypo::PackedSeq] step, saying 

[Hypo::PackedSeq] Error: Wrong base (Can not pack in 2 bits): Base code at 103517 in a sequence is not A, C, G, or T !
[Hypo::PackedSeq] Error: Wrong base (Can not pack in 2 bits): Base code at 212206 in a sequence is not A, C, G, or T !
[Hypo::PackedSeq] Error: Wrong base (Can not pack in 2 bits): Base code at 595921 in a sequence is not A, C, G, or T !

I believe the draft assembly contains nothing but ACGT, but Flye perfoms scaffolding and thus some sequences have Ns.

So I looked up the scaffolds in the draft assembly and found one scaffold has the first N at 103518th, another has it at 212207th, and the other has at 595922th. 

Is there a way to fix this problem? I used use racon x pilon but it takes long and consumes tons of memory. So it would be great if I (and people in my lab) can use hypo on my draft assemblies. 

Thanks!

**Comment by Ritu-Kundu** [comment]
Hi!

Thanks for using our polisher. Currently, Hypo can polish only contigs (not N's containing scaffolds). But it is something easy to fix. We will fix it and get back to you in a couple of days.

**Comment by Ritu-Kundu** [comment]
Hi @drk0311 ,

We have released the update that can handle Ns in the draft. Hope it will not run into any problem.

**Comment by drk0311** [comment]
Thank you! But came up with another problem.

Now I'm running the updated hypo, but it keeps producing errors but still runinng.
The error occurred right after loading the first batch of alignments like below;

`[Hypo::Hypo] Info: Number of alignments (Batch 0): loaded (93956) invalid (4958)`
`RESOURCES ([Hypo:Hypo]: Loaded alignments of Long reads. ): TIME= 28.5204 sec; PEAK RSS (so far)= 12630MB; CURRENT RSS (so far)= 12630MB.`
`RESOURCES ([Hypo:Hypo]: Long arms filling. ): TIME= 3.44978 sec; PEAK RSS (so far)= 12632MB; CURRENT RSS (so far)= 12632MB.`
`ERROR`
`ERROR`
`ERROR`
`...`

In the first kmc step, the message looks like kmc was running OK, but I don't see any kmc output files (I saw many in the previous run). Is it the reason, maybe?

**Comment by drk0311** [comment]
Oops, I found kmc outputs in aux directory.
So it seems kmc is successfully finished.

Anyway it still keeps running with producing lots of "ERROR"s.

**Comment by Ritu-Kundu** [comment]
It's weird. I could not find any print/error statement containing "ERROR" in the code. SDSL uses printing errors in that format but it should have accompanied some information on the nature of error.  Besides, SDSL is not used after long-arms filling. We will have to debug to get hold of the origin of this message. Please send us the files, if possible. We will add the debugging capability in the next release so that we don't have to ask for files.

**Comment by Ritu-Kundu** [comment]
Found the problem. It is in a customised function of spoa module. Do not worry about the message.; it's harmless. It just indicates that SISD Alignment engine will be used instead of SIMD. Will fix it.

**Comment by drk0311** [comment]
I see. That's good to hear. Thanks!

**Comment by Ritu-Kundu** [comment]
Hope you get good results in your experiments. Thanks again for using hypo.
