### ISSUE TITLE
Polishing transcriptomes

### ISSUE THREAD

**Issue by 000generic** [kensung-lab/hypo#7]
Hi!  

I was wondering if there are any modifications needed / that you recommend for polishing a PacBio or ONT de novo transcriptome assembly using Illumina reads (and the long-reads used to build the initial assembly) for polishing?

Thank you :)
Eric

**Comment by Ritu-Kundu** [comment]
Hi Eric,

Currently, Hypo doesn't support transcriptome-polishing. Hopefully we will work on making Hypo to work with Transcriptomes as well. Thanks for your interest.

**Comment by 000generic** [comment]
Ok!  If you do - great if you can update here. I would love to give it a try.

Thank you,
Eric

**Comment by Ritu-Kundu** [comment]
Sure! Thanks.
